package com.volley.manager.data

import android.content.Context
import androidx.room.*
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.coroutines.flow.Flow

enum class EventType { TRAINING, MATCH, EXCEPTIONAL }
enum class AttendanceStatus { PRESENT, ABSENT, LATE, EXCUSED }

@Entity(tableName = "players")
data class Player(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val firstName: String,
    val lastName: String,
    val age: Int,
    val position: String,
    val isGuest: Boolean = false,
    val email: String = "",
    val phone: String = "",
    val heightCm: Int? = null,
    val jerseyNumber: Int? = null,
    val notes: String = "",
    val serviceRating: Int = 0,
    val receptionRating: Int = 0,
    val settingRating: Int = 0,
    val attackRating: Int = 0,
    val blockRating: Int = 0,
    val defenseRating: Int = 0,
    val motivationRating: Int = 0,
    val techniqueRating: Int = 0
)

@Entity(tableName = "events")
data class VolleyEvent(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val type: EventType,
    val startsAt: Long,
    val durationMinutes: Int,
    val recurrenceDays: String = "",
    val recurrenceEndAt: Long? = null,
    val cancelled: Boolean = false,
    // Groups every occurrence generated by the same "add event" call (a recurring
    // series or a single standalone event) so a whole series can be targeted at once,
    // e.g. to delete "this and future occurrences".
    val seriesId: String? = null
)

@Entity(tableName = "event_guests", primaryKeys = ["playerId", "eventId"])
data class EventGuest(val playerId: Long, val eventId: Long)

@Entity(tableName = "attendance", primaryKeys = ["playerId", "eventId"])
data class Attendance(
    val playerId: Long,
    val eventId: Long,
    val status: AttendanceStatus = AttendanceStatus.PRESENT
)

@Entity(tableName = "absences")
data class Absence(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val playerId: Long,
    val startsAt: Long,
    val endsAt: Long,
    val reason: String
)

@Entity(tableName = "feedback")
data class Feedback(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val category: String,
    val title: String,
    val details: String,
    val createdAt: Long = System.currentTimeMillis()
)

@Dao
interface PlayerDao {
    @Query("SELECT * FROM players ORDER BY lastName, firstName")
    fun observeAll(): Flow<List<Player>>
    @Insert suspend fun insert(player: Player): Long
    @Insert suspend fun insertAll(players: List<Player>)
    @Update suspend fun update(player: Player)
    @Delete suspend fun delete(player: Player)
    @Query("DELETE FROM players") suspend fun deleteAll()
}

@Dao
interface EventDao {
    @Query("SELECT * FROM events ORDER BY startsAt")
    fun observeAll(): Flow<List<VolleyEvent>>
    @Insert suspend fun insert(event: VolleyEvent)
    @Insert suspend fun insertAll(events: List<VolleyEvent>)
    @Update suspend fun update(event: VolleyEvent)
    @Query("DELETE FROM events") suspend fun deleteAll()
    @Query("DELETE FROM events WHERE id = :id") suspend fun deleteById(id: Long)
    @Query("DELETE FROM events WHERE seriesId = :seriesId AND startsAt >= :fromStartsAt")
    suspend fun deleteSeriesFrom(seriesId: String, fromStartsAt: Long)
}

@Dao
interface EventGuestDao {
    @Query("SELECT * FROM event_guests")
    fun observeAll(): Flow<List<EventGuest>>
    @Insert(onConflict = OnConflictStrategy.REPLACE) suspend fun add(guest: EventGuest)
    @Insert(onConflict = OnConflictStrategy.REPLACE) suspend fun insertAll(guests: List<EventGuest>)
    @Delete suspend fun remove(guest: EventGuest)
    @Query("DELETE FROM event_guests") suspend fun deleteAll()
    @Query("DELETE FROM event_guests WHERE eventId = :eventId") suspend fun deleteForEvent(eventId: Long)
    @Query("DELETE FROM event_guests WHERE eventId IN (SELECT id FROM events WHERE seriesId = :seriesId AND startsAt >= :fromStartsAt)")
    suspend fun deleteForSeriesFrom(seriesId: String, fromStartsAt: Long)
}

@Dao
interface AttendanceDao {
    @Query("SELECT * FROM attendance")
    fun observeAll(): Flow<List<Attendance>>
    @Insert(onConflict = OnConflictStrategy.REPLACE) suspend fun save(attendance: Attendance)
    @Insert(onConflict = OnConflictStrategy.REPLACE) suspend fun insertAll(attendance: List<Attendance>)
    @Query("DELETE FROM attendance") suspend fun deleteAll()
    @Query("DELETE FROM attendance WHERE eventId = :eventId") suspend fun deleteForEvent(eventId: Long)
    @Query("DELETE FROM attendance WHERE eventId IN (SELECT id FROM events WHERE seriesId = :seriesId AND startsAt >= :fromStartsAt)")
    suspend fun deleteForSeriesFrom(seriesId: String, fromStartsAt: Long)
}

@Dao
interface AbsenceDao {
    @Insert suspend fun insert(absence: Absence)
    @Insert suspend fun insertAll(absences: List<Absence>)
    @Query("SELECT * FROM absences")
    fun observeAll(): Flow<List<Absence>>
    @Query("DELETE FROM absences") suspend fun deleteAll()
}

@Dao
interface FeedbackDao {
    @Query("SELECT * FROM feedback ORDER BY createdAt DESC")
    fun observeAll(): Flow<List<Feedback>>
    @Insert suspend fun insert(feedback: Feedback)
    @Insert suspend fun insertAll(feedback: List<Feedback>)
    @Query("DELETE FROM feedback") suspend fun deleteAll()
}

private val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE players ADD COLUMN email TEXT NOT NULL DEFAULT ''")
        db.execSQL("ALTER TABLE players ADD COLUMN phone TEXT NOT NULL DEFAULT ''")
        db.execSQL("ALTER TABLE players ADD COLUMN heightCm INTEGER")
        db.execSQL("ALTER TABLE players ADD COLUMN jerseyNumber INTEGER")
        db.execSQL("ALTER TABLE players ADD COLUMN notes TEXT NOT NULL DEFAULT ''")
    }
}

private val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE players ADD COLUMN serviceRating INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE players ADD COLUMN receptionRating INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE players ADD COLUMN settingRating INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE players ADD COLUMN attackRating INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE players ADD COLUMN blockRating INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE players ADD COLUMN defenseRating INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE players ADD COLUMN motivationRating INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE players ADD COLUMN techniqueRating INTEGER NOT NULL DEFAULT 0")
    }
}

private val MIGRATION_6_7 = object : Migration(6, 7) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE events ADD COLUMN seriesId TEXT")

        // Existing events were never linked together, so recover the grouping
        // heuristically: events sharing the same title/type/duration and starting
        // exactly one week apart are treated as the same recurring series.
        data class Row(val id: Long, val title: String, val type: String, val duration: Int, val startsAt: Long)
        val rows = mutableListOf<Row>()
        db.query("SELECT id, title, type, durationMinutes, startsAt FROM events ORDER BY startsAt").use { cursor ->
            val idIdx = cursor.getColumnIndexOrThrow("id")
            val titleIdx = cursor.getColumnIndexOrThrow("title")
            val typeIdx = cursor.getColumnIndexOrThrow("type")
            val durationIdx = cursor.getColumnIndexOrThrow("durationMinutes")
            val startsAtIdx = cursor.getColumnIndexOrThrow("startsAt")
            while (cursor.moveToNext()) {
                rows.add(
                    Row(
                        cursor.getLong(idIdx), cursor.getString(titleIdx), cursor.getString(typeIdx),
                        cursor.getInt(durationIdx), cursor.getLong(startsAtIdx)
                    )
                )
            }
        }

        val oneWeekMs = 7L * 24 * 60 * 60 * 1000
        val toleranceMs = 60L * 60 * 1000 // tolerate DST shifts around the exact week mark
        rows.groupBy { Triple(it.title, it.type, it.duration) }.values.forEach { group ->
            var currentSeriesId: String? = null
            var previousStartsAt: Long? = null
            group.sortedBy { it.startsAt }.forEach { row ->
                val continuesSeries = previousStartsAt != null &&
                    kotlin.math.abs((row.startsAt - previousStartsAt!!) - oneWeekMs) <= toleranceMs
                if (!continuesSeries) currentSeriesId = java.util.UUID.randomUUID().toString()
                db.execSQL("UPDATE events SET seriesId = ? WHERE id = ?", arrayOf(currentSeriesId, row.id))
                previousStartsAt = row.startsAt
            }
        }
    }
}

@Database(entities = [Player::class, VolleyEvent::class, EventGuest::class, Attendance::class, Absence::class, Feedback::class], version = 7, exportSchema = false)
@TypeConverters(Converters::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun players(): PlayerDao
    abstract fun events(): EventDao
    abstract fun eventGuests(): EventGuestDao
    abstract fun attendance(): AttendanceDao
    abstract fun absences(): AbsenceDao
    abstract fun feedback(): FeedbackDao

    companion object {
        fun create(context: Context): AppDatabase = Room.databaseBuilder(
            context, AppDatabase::class.java, "volley-manager.db"
        ).addMigrations(MIGRATION_4_5, MIGRATION_5_6, MIGRATION_6_7).build()
    }
}

class Converters {
    @TypeConverter fun eventType(value: EventType) = value.name
    @TypeConverter fun eventType(value: String) = EventType.valueOf(value)
    @TypeConverter fun attendanceStatus(value: AttendanceStatus) = value.name
    @TypeConverter fun attendanceStatus(value: String) = AttendanceStatus.valueOf(value)
}
